# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import usuarios_pb2 as usuarios__pb2


class SistemaStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.VerifHome = channel.unary_unary(
                '/Sistema/VerifHome',
                request_serializer=usuarios__pb2.SolicitudHome.SerializeToString,
                response_deserializer=usuarios__pb2.RespuestaHome.FromString,
                )
        self.Login = channel.unary_unary(
                '/Sistema/Login',
                request_serializer=usuarios__pb2.SolicitudLogin.SerializeToString,
                response_deserializer=usuarios__pb2.RespuestaLogin.FromString,
                )
        self.Create = channel.unary_unary(
                '/Sistema/Create',
                request_serializer=usuarios__pb2.SolicitudCreate.SerializeToString,
                response_deserializer=usuarios__pb2.RespuestaCreate.FromString,
                )
        self.Read = channel.unary_stream(
                '/Sistema/Read',
                request_serializer=usuarios__pb2.SolicitudRead.SerializeToString,
                response_deserializer=usuarios__pb2.RespuestaRead.FromString,
                )
        self.Write = channel.unary_unary(
                '/Sistema/Write',
                request_serializer=usuarios__pb2.SolicitudWrite.SerializeToString,
                response_deserializer=usuarios__pb2.RespuestaWrite.FromString,
                )
        self.Rename = channel.unary_unary(
                '/Sistema/Rename',
                request_serializer=usuarios__pb2.SolicitudRename.SerializeToString,
                response_deserializer=usuarios__pb2.RespuestaRename.FromString,
                )
        self.Remove = channel.unary_unary(
                '/Sistema/Remove',
                request_serializer=usuarios__pb2.SolicitudRemove.SerializeToString,
                response_deserializer=usuarios__pb2.RespuestaRemove.FromString,
                )
        self.Mkdir = channel.unary_unary(
                '/Sistema/Mkdir',
                request_serializer=usuarios__pb2.SolicitudMkdir.SerializeToString,
                response_deserializer=usuarios__pb2.RespuestaMkdir.FromString,
                )
        self.Rmdir = channel.unary_unary(
                '/Sistema/Rmdir',
                request_serializer=usuarios__pb2.SolicitudRmdir.SerializeToString,
                response_deserializer=usuarios__pb2.RespuestaRmdir.FromString,
                )
        self.Readdir = channel.unary_stream(
                '/Sistema/Readdir',
                request_serializer=usuarios__pb2.SolicitudReaddir.SerializeToString,
                response_deserializer=usuarios__pb2.RespuestaReaddir.FromString,
                )


class SistemaServicer(object):
    """Missing associated documentation comment in .proto file."""

    def VerifHome(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Read(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Write(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Rename(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Remove(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Mkdir(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Rmdir(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Readdir(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SistemaServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'VerifHome': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifHome,
                    request_deserializer=usuarios__pb2.SolicitudHome.FromString,
                    response_serializer=usuarios__pb2.RespuestaHome.SerializeToString,
            ),
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=usuarios__pb2.SolicitudLogin.FromString,
                    response_serializer=usuarios__pb2.RespuestaLogin.SerializeToString,
            ),
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=usuarios__pb2.SolicitudCreate.FromString,
                    response_serializer=usuarios__pb2.RespuestaCreate.SerializeToString,
            ),
            'Read': grpc.unary_stream_rpc_method_handler(
                    servicer.Read,
                    request_deserializer=usuarios__pb2.SolicitudRead.FromString,
                    response_serializer=usuarios__pb2.RespuestaRead.SerializeToString,
            ),
            'Write': grpc.unary_unary_rpc_method_handler(
                    servicer.Write,
                    request_deserializer=usuarios__pb2.SolicitudWrite.FromString,
                    response_serializer=usuarios__pb2.RespuestaWrite.SerializeToString,
            ),
            'Rename': grpc.unary_unary_rpc_method_handler(
                    servicer.Rename,
                    request_deserializer=usuarios__pb2.SolicitudRename.FromString,
                    response_serializer=usuarios__pb2.RespuestaRename.SerializeToString,
            ),
            'Remove': grpc.unary_unary_rpc_method_handler(
                    servicer.Remove,
                    request_deserializer=usuarios__pb2.SolicitudRemove.FromString,
                    response_serializer=usuarios__pb2.RespuestaRemove.SerializeToString,
            ),
            'Mkdir': grpc.unary_unary_rpc_method_handler(
                    servicer.Mkdir,
                    request_deserializer=usuarios__pb2.SolicitudMkdir.FromString,
                    response_serializer=usuarios__pb2.RespuestaMkdir.SerializeToString,
            ),
            'Rmdir': grpc.unary_unary_rpc_method_handler(
                    servicer.Rmdir,
                    request_deserializer=usuarios__pb2.SolicitudRmdir.FromString,
                    response_serializer=usuarios__pb2.RespuestaRmdir.SerializeToString,
            ),
            'Readdir': grpc.unary_stream_rpc_method_handler(
                    servicer.Readdir,
                    request_deserializer=usuarios__pb2.SolicitudReaddir.FromString,
                    response_serializer=usuarios__pb2.RespuestaReaddir.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Sistema', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Sistema(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def VerifHome(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Sistema/VerifHome',
            usuarios__pb2.SolicitudHome.SerializeToString,
            usuarios__pb2.RespuestaHome.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Sistema/Login',
            usuarios__pb2.SolicitudLogin.SerializeToString,
            usuarios__pb2.RespuestaLogin.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Sistema/Create',
            usuarios__pb2.SolicitudCreate.SerializeToString,
            usuarios__pb2.RespuestaCreate.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Read(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/Sistema/Read',
            usuarios__pb2.SolicitudRead.SerializeToString,
            usuarios__pb2.RespuestaRead.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Write(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Sistema/Write',
            usuarios__pb2.SolicitudWrite.SerializeToString,
            usuarios__pb2.RespuestaWrite.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Rename(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Sistema/Rename',
            usuarios__pb2.SolicitudRename.SerializeToString,
            usuarios__pb2.RespuestaRename.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Remove(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Sistema/Remove',
            usuarios__pb2.SolicitudRemove.SerializeToString,
            usuarios__pb2.RespuestaRemove.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Mkdir(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Sistema/Mkdir',
            usuarios__pb2.SolicitudMkdir.SerializeToString,
            usuarios__pb2.RespuestaMkdir.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Rmdir(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Sistema/Rmdir',
            usuarios__pb2.SolicitudRmdir.SerializeToString,
            usuarios__pb2.RespuestaRmdir.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Readdir(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/Sistema/Readdir',
            usuarios__pb2.SolicitudReaddir.SerializeToString,
            usuarios__pb2.RespuestaReaddir.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
